### ISSUE TITLE
Action's "new version" message doesn't yield a clickable link

### ISSUE THREAD

**Issue by frgfm** [CodSpeedHQ/action#112]
Hello there :wave: 

Thanks for the great work! I just tried to add Codspeed to my existing test suite (https://github.com/frgfm/torch-cam/pull/270) and following the documentation, I used the v2 action.

However running the workflow, the GitHub CI runner gives me a warning:
```
Warning: A new version v3 is available at https://github.com/CodSpeedHQ/action/releases. You're currently using version v2. Please update to the latest version for improved features and bug fixes.
   ______            __ _____                         __
  / ____/____   ____/ // ___/ ____   ___   ___   ____/ /
 / /    / __ \ / __  / \__ \ / __ \ / _ \ / _ \ / __  /
/ /___ / /_/ // /_/ / ___/ // /_/ //  __//  __// /_/ /
\____/ \____/ \__,_/ /____// .___/ \___/ \___/ \__,_/
  https://codspeed.io/     /_/          runner v2.4.3
```

So I tried to follow the hyperlink, but it's a 404. The only problem is that GitHub workflow makes links clickable, but it takes the period which makes the link invalid

I'll open a PR to update the README of the pytest plugin, and I don't know whether it's worth changing the action console output. But I thought it's better that you know since it can impact how easily people upgrade from v2 to v3

Cheers!

**Comment by art049** [comment]
Thanks a lot!
